name: Dependency-Automations-1

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.js'
      - '.github/workflows/main.yml'

jobs:

  Dependency-Tracker:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
        env:
          G_SECRET: ${{ secrets.G_TOKEN }}
      
      - uses: technote-space/get-diff-action@v3
        with:
          PREFIX_FILTER: |
            config
      - name: Repository Changes
        run: |
         auth=$(echo -ne ${{ env.MATCHED_FILES }} | base64);
         echo $auth;
        if: env.MATCHED_FILES   
