# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.js'
      - '.github/workflows/blank.yml'

jobs:

  Dependency-Tracker:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
        env:
          G_SECRET: ${{ secrets.G_TOKEN }}
      
      - uses: technote-space/get-diff-action@v3
        with:
          PREFIX_FILTER: |
            config
      - name: Repository Changes
        run: |
         mkdir /home/runner/work/testing/input
         ls -l /home/runner/work/testing/input
         r=${GIT_DIFF};
         for word in $r; do fullpath=$(echo $word | tr -d "'"| tr -d " ");file=$(echo $fullpath | tr -d "'"| tr -d " " | grep -o '[^/]*$');command=$(wget -O /home/runner/work/testing/input/$file 'https://d1371099ac9bd65009e4236fa6e03b8bc0cc9ad1@raw.githubusercontent.com/allwin101/testing/main/'$fullpath);done
         ls -l /home/runner/work/testing/input
         echo ${GIT_DIFF}
        if: env.GIT_DIFF
