# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.js'
      - '.github/workflows/blank.yml'

jobs:

  Dependency-Tracker:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
        env:
          G_SECRET: ${{ secrets.G_TOKEN }}
      
      - uses: technote-space/get-diff-action@v3
        with:
          PREFIX_FILTER: |
            config
          SET_ENV_NAME_COUNT: GIT_COUNT_FILES
          SET_ENV_NAME_INSERTIONS: GIT_INSERT_LINES
          SET_ENV_NAME_DELETIONS: GIT_DELETE_LINES
          
      - name: Repository Changes
        run: |
         echo ${GIT_DIFF}
         echo ${GIT_COUNT_FILES}
         echo ${GIT_INSERT_LINES}
         echo ${GIT_DELETE_LINES}
        if: env.GIT_DIFF
