name: CI

on:
  push:
    branches:
      - main

jobs:

  Dependency-Tracker:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Clean job dir
        id: test_dir
        run: |
          echo "::set-output name=FOO::$(date)"
          
      - name: Use it
        run: echo ${{ steps.test_dir.outputs.FOO }}    
